
apiVersion: v1
kind: Service
metadata:
  name: hello-service
spec:
  selector:
    run: hello-deployment
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
    name: http
  type: NodePort

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hello-deployment
spec:
  selector:
    matchLabels:
      run: hello-deployment
  replicas: 4
  template:
    metadata:
      labels:
        run: hello-deployment
    spec:
      containers:
      - name: session
        image: repo.isw.la/springboot-hello-world-test:1.0.10
        ports:
        - containerPort: 8080

